### ISSUE TITLE
Update Etsy API endpoint

### ISSUE THREAD

**Issue by tw2113** [coreymcollins/Etsy-Product-Importer-for-WordPress#16]
Current:

```
https://openapi.etsy.com/v2/private/shops/{$this->store_id}/listings/active?sort_on=created&sort_order=down&api_key={$this->api_key}&limit=25
```

Appears to work with some minimal testing:

```
https://openapi.etsy.com/v2/shops/{$this->store_id}/listings/active?sort_on=created&sort_order=down&api_key={$this->api_key}&limit=25
```

@coreymcollins do you have any recollection at all as to why the "private" version of the API was used at all? Possibly Brian Richards' suggestion?

Curious if it's causing issues with returned count responses.

**Comment by coreymcollins** [comment]
I can't recall now why we may have used private when building this out initially.  It may have been that this allowed for a user's shop that may have been set to private, but that's just a quick guess right now.

**Comment by tw2113** [comment]
Closing. I'm not managing to come up with any actual benefit for this one.
