### ISSUE TITLE
Prefix or remove some CSS

### ISSUE THREAD

**Issue by tw2113** [coreymcollins/Etsy-Product-Importer-for-WordPress#3]
Not sure if it's still used at all, but the CSS selector for `.form-table td label {}` was causing some issues with CPTUI last night. If not used, may be worth cleaning up the CSS file a little, otherwise a prefix for the labels you're wanting to affect may be a good idea.

**Comment by coreymcollins** [comment]
Just pushed an update for this.  Thanks!
